### ISSUE TITLE
Oplog ENV-var is misnamed

### ISSUE THREAD

**Issue by arggh** [kontena/mongo-backup#4]
Currently, looking through the sources, the option for enabling `--oplog` setting for Mongodump is named `MONGODB_OPLOCK`, which I think is quite prone to cause problems.

**Comment by nevalla** [comment]
Thanks for reporting, need to fix that. Or do you want to make a PR?

**Comment by arggh** [comment]
https://github.com/kontena/mongo-backup/pull/6

**Comment by matti** [comment]
@nevalla merge that?

**Comment by matti** [comment]
@nevalla this can be closed?
